[tool.poetry]
name = "module-one-template"
version = "1.0.0"
description = "This is the first module of this Monorepo Template"
authors = [
    "Roberto Hernandez <betohr60@gmail.com>"
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
ipykernel = "6.21.*"
pandas = "^2.0.3"
mlflow = "^2.9.2"
